theme: jekyll-theme-leap-day
title: [Dr. Shengcai Liao]
description1: ["Acting Director of R&D, Principal Scientist, Senior Member, IEEE"]
description2: ["Inception Institute of Artificial Intelligence (IIAI), G42, Abu Dhabi, UAE"]
