theme: jekyll-theme-leap-day
title: [Dr. Shengcai Liao]
description1: ["Associate Professor, Senior Member, IEEE"]
description2: ["College of Information Technology (CIT), United Arab Emirates University (UAEU), Al Ain, UAE"]
