theme: jekyll-theme-leap-day
title: [Dr. Shengcai Liao]
description1: ["IEEE Fellow, IAPR Fellow, Associate Professor"]
description2: ["College of Information Technology (CIT), United Arab Emirates University (UAEU), Al Ain, UAE"]
